# Netlify配置文件

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# 单页面应用重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"